### ISSUE TITLE
UpdateEfficienciesAndDemand slow

### ISSUE THREAD

**Issue by Davidrxyang** [Davidrxyang/raines-2024-line-addition-problem#121]
I believe this function is what is taking up a ton of time, we may want to think about trying to optimize it. 

Also, since this function is more of an optimizing function, I would not consider it to be absolutely part of the core functionality. We may want to consider making this function toggle-able as another parameter in the config.

**Comment by henrydeng2002** [comment]
have an idea, should be able to get this fixed tomorrow

**Comment by Davidrxyang** [comment]
#124
